### ISSUE TITLE
Use Travis CI Cron Jobs

### ISSUE THREAD

**Issue by l2dy** [repology/homebrew-json-gen-travis#1]
See https://docs.travis-ci.com/user/cron-jobs/. But you can't use GitHub Releases with this.

**Comment by AMDmi3** [comment]
> See https://docs.travis-ci.com/user/cron-jobs/

Yes, I've already tried that.

> But you can't use GitHub Releases with this.

Correct, and the main point of this repo is using GH releases, e.g. not bothering with setting up own infrastructure for building or storing homebrew metadata. Since travis cron doesn't work with it, we can't use it.

I also consider this a Travis [bug](https://github.com/travis-ci/travis-ci/issues/8146).

**Comment by l2dy** [comment]
You can use https://docs.travis-ci.com/user/deployment/pages/ instead of releases.

**Comment by AMDmi3** [comment]
I don't want set up even more crutches. This repo is a temporary solution anyway, because homebrew metadata should be generated, managed and distributed by homebrew community.

**Comment by l2dy** [comment]
My point is that I'm willing to work on this and submit a PR, but I should seek for your approval first to avoid wasted effort. Since I'm not part of the "Homebrew community", should I just close the issue?

**Comment by AMDmi3** [comment]
My point was not wasting my time (which could be spent on repology directly) on this without noticeable gain (which would be getting rid of this repo by e.g. switching to official data). However if you want to work on it I'll just add you to collaborators.

**Comment by l2dy** [comment]
I don't seem to have the permission to enable cron jobs.

**Comment by AMDmi3** [comment]
Not sure what should be done to allow you to manage travis build, but I've enabled cron. master branch, daily run.

**Comment by l2dy** [comment]
Thanks. After syncing my Travis CI account I can change settings now.
